CREATE TABLE [dbo].[MarketItems]
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_MarketItems PRIMARY KEY,
	ItemId INT NOT NULL CONSTRAINT FK_MarketItems_ItemID REFERENCES UnturnedItems(ItemId),
	Metadata VARBINARY(128) NOT NULL,
	Quality TINYINT NOT NULL,
	Amount TINYINT NOT NULL,
	Price DECIMAL(9, 2) NOT NULL,
	SellerId VARCHAR(255) NOT NULL,
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_MarketItems_CreateDate DEFAULT SYSDATETIME(),
	IsSold BIT NOT NULL CONSTRAINT DF_MarketItems_IsSold DEFAULT 0,
	BuyerId VARCHAR(255) NULL,
	SoldDate DATETIME2(0) NULL,
	IsClaimed BIT NOT NULL CONSTRAINT DF_MarketItems_IsClaimed DEFAULT 0,
	ClaimDate DATETIME2(0) NULL
);