CREATE TABLE dbo.Products 
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_Products PRIMARY KEY,
	Title NVARCHAR(255) NOT NULL,
	Description NVARCHAR(2555) NOT NULL,
	Price DECIMAL(9, 2) NOT NULL,
	Icon VARBINARY(MAX) NULL,
	MaxPurchases INT NOT NULL,
	Enabled BIT NOT NULL
);