CREATE TABLE [dbo].[Settings]
(
	SettingId VARCHAR(255) NOT NULL PRIMARY KEY,
	SettingValue VARCHAR(255) NULL,
	Help VARCHAR(1000) NULL,
	IsAdmin BIT NOT NULL CONSTRAINT DK_Settings_IsAdmin DEFAULT 0
);
